server:
    port: 8080
    servlet:
        encoding:
            force: true
            enabled: true
            charset: UTF-8

management:
    port: 7002

spring:
    jpa:
        hibernate:
            naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
    datasource:
        initialize: true
        sqlScriptEncoding: UTF-8
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
        pathmatch:
            matching-strategy: ant_path_matcher
    profiles:
        active: dev
    main:
        allow-bean-definition-overriding: true